version: '3.13'

services:
  backend:
    build:
      context: ./backend # Relative to this docker-compose.yml file
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mounts the host's backend directory to /app in the container
    environment:
      - MONGO_URL=mongodb://mongo:27017/bot_club_db # Added a database name
      - NODE_ENV=development
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend # Relative to this docker-compose.yml file
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Mounts the host's frontend directory to /app in the container
      - /app/node_modules # Preserves node_modules installed in the image
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:6.0 # Using a specific version is good practice
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: {}